// frontend/src/app/features/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AuthService } from '@app/core/auth/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="min-h-screen bg-gray-100">
      <!-- Header -->
      <header class="bg-white shadow">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div class="flex justify-between items-center">
            <h1 class="text-2xl font-bold text-gray-800">
              IT Credential Management
            </h1>
            <button
              (click)="onLogout()"
              class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded"
            >
              Logout
            </button>
          </div>
        </div>
      </header>

      <!-- Main Content -->
      <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        @if (user$ | async as user) {
          <div class="bg-white rounded-lg shadow p-8">
            <h2 class="text-3xl font-bold mb-4">Welcome, {{ user.email }}!</h2>
            <p class="text-gray-600 mb-4">Role: <span class="font-semibold capitalize">{{ user.role }}</span></p>
            
            <div class="mt-8 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              <div class="bg-blue-50 p-6 rounded-lg border border-blue-200">
                <h3 class="text-lg font-bold mb-2">Clients</h3>
                <p class="text-gray-600">Manage your client accounts</p>
              </div>
              
              <div class="bg-green-50 p-6 rounded-lg border border-green-200">
                <h3 class="text-lg font-bold mb-2">Credentials</h3>
                <p class="text-gray-600">View and manage credentials securely</p>
              </div>
              
              <div class="bg-purple-50 p-6 rounded-lg border border-purple-200">
                <h3 class="text-lg font-bold mb-2">Devices</h3>
                <p class="text-gray-600">View devices and sites</p>
              </div>
            </div>

            <div class="mt-8 bg-yellow-50 border border-yellow-200 p-4 rounded-lg">
              <p class="text-sm text-gray-700">
                🔒 <strong>Security Notice:</strong> This application is ISO 27001 compliant. 
                All credentials are encrypted and audited. Do not share your login credentials.
              </p>
            </div>
          </div>
        }
      </main>
    </div>
  `,
  styleUrls: ['./dashboard.component.scss'],
})
export class DashboardComponent {
  user$ = this.authService.user$;

  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  onLogout(): void {
    this.authService.logout().subscribe({
      next: () => {
        this.router.navigate(['/auth/login']);
      },
      error: (err) => {
        console.error('Logout error:', err);
        this.router.navigate(['/auth/login']);
      },
    });
  }
}

// app/src/app/dashboard/page.tsx
import { redirect } from "next/navigation";
import { getSession } from "@/lib/auth/session";
import { Card } from "@/components/ui/Card";
import { prisma } from "@/lib/database/prisma";
import Link from "next/link";

export default async function DashboardPage() {
  const session = await getSession();

  if (!session?.mfa) {
    redirect("/auth/login");
  }

  const [clientsCount, credentialsCount, devicesCount] = await Promise.all([
    prisma.client.count(),
    prisma.credential.count(),
    prisma.device.count(),
  ]);

  return (
    <main className="min-h-screen bg-base-200 p-4 md:p-8">
      <div className="max-w-6xl mx-auto space-y-6">
        <header className="navbar bg-base-100 border border-base-300 rounded-box">
          <div className="flex-1">
            <h1 className="text-xl font-semibold">IT Credential Management</h1>
          </div>
          <div className="flex-none">
            <form action="/api/auth/logout" method="post">
              <button className="btn btn-outline btn-sm" type="submit">
                Logout
              </button>
            </form>
          </div>
        </header>

        <section className="alert border border-base-300">
          <span>
            Utente: <strong>{session.email}</strong> — Ruolo: <strong>{session.role}</strong>
          </span>
        </section>

        <section className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <Card title="Clienti">
            <p className="text-sm opacity-70">Totale: {clientsCount}</p>
            <div className="card-actions justify-end mt-2">
              <Link className="btn btn-sm btn-outline" href="/clients">
                Apri
              </Link>
            </div>
          </Card>
          <Card title="Credenziali">
            <p className="text-sm opacity-70">Totale: {credentialsCount}</p>
            <div className="card-actions justify-end mt-2">
              <Link className="btn btn-sm btn-outline" href="/credentials">
                Apri
              </Link>
            </div>
          </Card>
          <Card title="Device">
            <p className="text-sm opacity-70">Totale: {devicesCount}</p>
            <div className="card-actions justify-end mt-2">
              <Link className="btn btn-sm btn-outline" href="/devices">
                Apri
              </Link>
            </div>
          </Card>
        </section>

        <section className="alert alert-info justify-between">
          <span>Conforme ai requisiti operativi ISO 27001 (audit trail + MFA + RBAC).</span>
          <div className="flex items-center gap-2">
            <Link className="btn btn-sm btn-ghost" href="/sites">
              Siti
            </Link>
            {session.role === "admin" ? (
              <Link className="btn btn-sm btn-ghost" href="/audit">
                Audit
              </Link>
            ) : null}
          </div>
        </section>
      </div>
    </main>
  );
}
